### PR TITLE
add host-side examples

### PR DESCRIPTION
**Pull request by niermann999**
I quickly added a few host-side examples. Do you want to present the full chain along with the CUDA propagation? Or do you want to add the material description or something else?

### CODE REVIEW

**Comment by beomki-yeo** [comment]
I added you as a collaboration so that you can add codes without my permission.

> Do you want to present the full chain along with the CUDA propagation? 

Yes but very minimally. What's in `propagation_cuda.cpp` and `propagation_cpu.cpp` is almost everything that I want to present tomorrow. I don't think I will talk about detector or geometry in depth.

Actually I expected you show how to build a detector from scratch. Even a very simple two-planes muon veto system would be great.  


For example:
1. How to define a detector metadata
2. How to add surfaces/volumes to the detector

**Comment by niermann999** [comment]
I wasn't so sure how interesting actual detector building in detray is, since apart from the toy geometry and the telescope, all of the 'client' geometries will not be built in detray but will come directly from ACTS most likely. Besides, as soon as I have time, I plan to change quite a bit in how the detector is built...

But it's definitely a good idea to mention the metadata

**Comment by niermann999** [comment]
> Yes but very minimally. What's in `propagation_cuda.cpp` and `propagation_cpu.cpp` is almost everything that I want to present tomorrow. I don't think I will talk about detector or geometry in depth.

I was just wondering, because it has a lot of overlap with the ```full_chain``` example, only that I also planned to walk through the configuration options (policies, step size constraints, aborters/actors etc.)

**Comment by beomki-yeo** [comment]
> all of the 'client' geometries will not be built in detray but will come directly from ACTS most likely

Right... BTW, I thought we will replace ACTS geometry with detray in the future and remove detray afterwards. Maybe I should have brought it up today when people were just talking about traccc.

**Comment by beomki-yeo** [comment]
> because it has a lot of overlap with the full_chain example,

Ah In that case, I will just go through the cuda exmaple only

**Comment by niermann999** [comment]
> Right... BTW, I thought we will replace ACTS geometry with detray in the future and remove detray afterwards. Maybe I should have brought it up today when people were just talking about traccc.

From what I understand, the conversion and automatic geometry building that is already in ACTS will be used and there will be an interface from an ACTS tracking geometry to a detray one. I think the discussion today went rather in the direction of using detray as a submodule. In that case, I guess, the repository will stay its own thing?

**Comment by niermann999** [comment]
> Ah In that case, I will just go through the cuda exmaple only

Or you just merge the full chain example into the cuda propagation example. Whatever you prefer :)

**Comment by beomki-yeo** [comment]
I understood it like using detray as a submodule "temporarily" at the moment. But I don't have strong opinion on this

**Comment by niermann999** [comment]
> I understood it like using detray as a submodule "temporarily" at the moment. But I don't have strong opinion on this

Oh, I see, I don't know actually. I also don't have a strong opinion on that. Let's see how it turns out :D

**Comment by beomki-yeo** [comment]
Yeah. Actually replacing it is almost a mission impossible thinking about all the detector-related plugins implemented in ACTS.

> Or you just merge the full chain example into the cuda propagation example. Whatever you prefer :)

Then I will merge them. Only difference between them  is  overstep_tolerance/step_constraint/rk_tolerance I suppose

**Comment by niermann999** [comment]
> Only difference between them is overstep_tolerance/step_constraint/rk_tolerance I suppose

Yes, I thought we should also show that in a full chain example

**Pull request merged**
